apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-disk-rules
  namespace: monitoring
spec:
  groups:
  - name: Data磁盘监控
    rules:
    - alert: Data磁盘使用率过高
      annotations:
        detail:  "{{$labels.instance}}: 磁盘:{{$labels.mountpoint}}使用率高于75% (当前值: {{ $value }})"
        summary: "{{$labels.instance}}: 磁盘使用率过高"
      expr: |
        ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"} ) / node_filesystem_size_bytes{mountpoint="/"} * 100) > 75
      for: 1m
      labels:
        severity: 严重
  - name: Boot磁盘监控
    rules:
    - alert: Boot磁盘使用率过高
      annotations:
        detail:  "{{$labels.instance}}: 磁盘:{{$labels.mountpoint}}使用率高于80% (当前值: {{ $value }})"
        summary: "{{$labels.instance}}: 磁盘使用率过高"
      expr: |
        ((node_filesystem_size_bytes{mountpoint="/boot"} - node_filesystem_free_bytes{mountpoint="/boot"} ) / node_filesystem_size_bytes{mountpoint="/boot"} * 100) > 80
      for: 1m
      labels:
        severity: 严重  